services:
  web:
    build:
      context: ./sadonsclub
      dockerfile: Dockerfile.prod
    image: sadonsclub:1.0.0
    command: gunicorn sadonsclub.wsgi:application --bind 0.0.0.0:8000 --access-logfile '-' 
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/sadonsclub/static
    env_file:
      - ./sadonsclub/.env.prod
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sadonsclub_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - data:/var/lib/postgresql/data/
  
  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - static_volume:/sadonsclub/static
    ports:
      - 8001:80
    depends_on:
      - web

volumes:
  data:
  static_volume: