# Generated by Django 5.1 on 2024-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='bonuses',
            field=models.IntegerField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='money',
            field=models.FloatField(default=0, verbose_name='Деньги'),
        ),
    ]
