# Generated by Django 5.1 on 2024-09-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.BooleanField(default=False, verbose_name='Забронирован')),
                ('is_active', models.BooleanField(default=True, verbose_name='Рабочий')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='bookings.category')),
            ],
            options={
                'verbose_name': 'компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время бронирования')),
                ('booked_from', models.TimeField(verbose_name='Дата начала бронирования')),
                ('booked_until', models.TimeField(verbose_name='Дата окончания бронирования')),
                ('booked_to_date', models.DateField(verbose_name='Дата предстоящего бронирования')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('computer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.computers')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
